#!/bin/bash
source /usr/share/yunohost/helpers
app=openvpn
#source /etc/yunohost/apps/$app/scripts/_common.sh

#is_upnp=$1
#is_ipv6=$2

configure_firewall () {
    ip4ranges=$(ynh_app_setting_get $app ip4ranges | tr " " "\n")
    iface=$(ynh_app_setting_get $app iface)
    sudo iptables -t filter -$1 FORWARD -i "${iface}" -o tun0 -m state --state ESTABLISHED,RELATED -j ACCEPT

    sudo iptables -t filter -$1 FORWARD -i tun0 -o "${iface}" -m state --state ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -$1 FORWARD -i tun0 -j ACCEPT


}

add_firewall_rules () {
    configure_firewall A
}
add_firewall_rules
