#!/bin/bash

app=$1
new_users=$2

if [[ "openvpn" = "$app" ]];
then
  if (echo "$new_users"|grep -q ",");then
    search_filter="(\&(\&(uid=%u)(objectClass=mailAccount))(|"
    for user in ${new_users//,/ };do
      search_filter="$search_filter(uid=$user)"
    done
    search_filter="$search_filter))"
  else
    search_filter="(\&(\&(uid=%u)(objectClass=mailAccount))(uid=$new_users))"
  fi
  sudo sed -i "s/SearchFilter .*/SearchFilter \"$search_filter\"/g" /etc/openvpn/auth/ldap.conf
  sudo systemctl restart openvpn.service
fi
