#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Source YNH helpers
. /usr/share/yunohost/helpers

backup_dir=$1

# Get app instance name
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
local_path=$(ynh_app_setting_get $app local_path)

my_ynh_backup () {
    ynh_backup $@
    echo $2 $1 >> $backup_dir/list    
}

# Copy the app files
my_ynh_backup "$local_path" "sources"
my_ynh_backup "/etc/openvpn" "etc"
my_ynh_backup "/etc/yunohost/certs/${domain}/dh.pem" "certs/dh.pem"

# Copy the conf files
my_ynh_backup "/etc/openvpn/yunohost.conf" "conf/yunohost.conf"
my_ynh_backup "/etc/sysctl.d/openvpn.conf" "conf/sysctl"
my_ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "conf/nginx.conf"
my_ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "conf/php-fpm.conf"
my_ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "conf/php-fpm.ini"
my_ynh_backup "/etc/fail2ban/jail.d/${app}.conf" "conf/fail2ban-jail.conf"
my_ynh_backup "/etc/fail2ban/filter.d/$app.conf" "conf/fail2ban-filter.conf"
my_ynh_backup "/etc/logrotate.d/$app.conf" "conf/logrotate.conf"

# Copy log
my_ynh_backup "/var/log/openvpn" "log"
