#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

ynh_trap_on

export app=$YNH_APP_INSTANCE_NAME
export user=$app
export webuser="${user}web"

# Retrieve arguments
ynh_export domain path ip4ranges dedicated_ip
ynh_find_port 1194
export port=$port
export local_path=/var/www/$app
export iface=$(ip r|awk '/default/ { print $5 }')

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================
ynh_check_var "$app" "app name not set"
#ynh_user_exists "$admin" || ynh_die "User does not exist: $admin"
ynh_normalize_url_path "$path"
ynh_path_validity "$domain$path"
ynh_local_path_available "$local_path"
check_iptables
check_tun_available
check_ip4ranges $ip4ranges


#=================================================
# SETUP THE APP BY MODIFYING THE SYSTEM
#=================================================
ynh_save_args ip4ranges port local_path iface dedicated_ip

# Install official debian package
ynh_app_dependencies openvpn,openvpn-auth-ldap,netmask

# Create DH for main domain
dh_size=1024
info "Generate dhparam(${dh_size}) file, this step may be long..."
sudo openssl dhparam -out "/etc/yunohost/certs/${domain}/dh.pem" $dh_size > /dev/null
sudo openvpn --genkey --secret /etc/openvpn/ta.key

# Install configured files and restart services 
setup_and_restart
