#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

ynh_trap_on

export app=$YNH_APP_INSTANCE_NAME
export user=$app
export webuser="${user}web"

export domain=$(ynh_app_setting_get $app domain)
domain=${prefix:-$(cat /etc/yunohost/current_host)}
export path=$(ynh_app_setting_get $app path)
path=${path:-/openvpn/}
export local_path=$(ynh_app_setting_get $app local_path)
local_path=${local_path:-/var/www/$app}
export iface=$(ynh_app_setting_get $app iface)
iface=${iface:-$(ip r|awk '/default/ { print $5 }')}
export port=$(ynh_app_setting_get $app port)
port=${port:-1194}
export ip4ranges=$(ynh_app_setting_get $app ip4ranges)
ip4ranges=${ip4ranges:-10.0.0.8/24}
export dynamic_ip=$(ynh_app_setting_get $app dynamic_ip)
dynamic_ip=${dynamic_ip:-false}


version=$(ynh_read_json "/etc/yunohost/apps/$app/manifest.json" 'version' 2> /dev/null || echo '2.3.4-1')
last_version=$(ynh_read_manifest 'version')

ynh_exit_if_up_to_date
ynh_check_var "$app" "app name not set"
ynh_normalize_url_path "$path"

if [ "${version}" = "2.3.4-1" ]; then
    ynh_save_args domain path ip4ranges port local_path iface dynamic_ip 

    # Install official debian package
    ynh_app_dependencies openvpn,openvpn-auth-ldap,netmask

    # Delete old cron (replace by a iptables hooks)
    sudo rm -f /etc/openvpn/yunohost.cron

    # Install configured files and restart services 
    setup_and_restart

    sudo mv /var/log/openvpn.log /var/log/openvpn/status.log
fi

if [ "${version}" = "2.3.4-2" ]; then
    sudo touch /etc/openvpn/crl.pem
    sudo mkdir -p /etc/openvpn/users
    sudo touch /etc/openvpn/ip4_attribution.csv
    sudo cp ../conf/handler.sh /etc/openvpn/handler.sh
    sudo chown -R $user: /etc/openvpn
    sudo chmod 640 /etc/openvpn/ip4_attribution.csv
    sudo chmod u+x /etc/openvpn/handler.sh  
fi
