#!/bin/bash

domain=$(cat /etc/yunohost/current_host)

# Find network interface (usually eth0/1 or wlan0)
iface=$(ifconfig -a| grep -v ^$| grep ^[a-z*] | awk '{print $1}' | grep eth | head -n 1)
if [[ ! $? -eq 0 ]]; then
    iface=$(ifconfig -a| grep -v ^$| grep ^[a-z*] | awk '{print $1}' | grep wlan | head -n 1)
    if [[ ! $? -eq 0 ]]; then
        echo "Wrong network interface"
        exit 1
    fi
fi

# Upgrade official debian package
sudo apt-get install openvpn openvpn-auth-ldap -y -qq

# Upgrade configurations
sed -i "s@DOMAINTOCHANGE@$domain@g" ../conf/yunohost.conf
sudo cp ../conf/yunohost.conf /etc/openvpn/
sudo cp ../conf/ldap.conf /etc/openvpn/auth/

# IP forwarding
sudo cp ../conf/sysctl /etc/sysctl.d/openvpn.conf
sudo sysctl -p /etc/sysctl.d/openvpn.conf

# Cron iptables
sed -i "s@IFACETOCHANGE@$iface@g" ../conf/cron
sudo cp ../conf/cron /etc/openvpn/yunohost.cron
echo "*/5 * * * * root bash /etc/openvpn/yunohost.cron" | sudo tee /etc/cron.d/yunohost-openvpn
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o $iface -j MASQUERADE

# Restart
sudo service openvpn restart
